version: '2.4'

services:
  ffixp_router:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./generated/bird:/etc/bird
      - ./bird:/etc/bird/static
      - ./generated/wireguard/interfaces:/etc/wireguard
      - ./scripts:/scripts
      - '/lib/modules:/lib/modules:ro'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    privileged: true
